import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNav from "../components/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Order Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SideNav>{children}</SideNav>;
}
