import type { Metadata } from "next";
import SideNav from "../components/sideNav";

export const metadata: Metadata = {
  title: "data Pembelian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SideNav>{children}</SideNav>;
}
