import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNav from "../components/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNav>{children}</SideNav>
      </body>
    </html>
  );
}
